### ISSUE TITLE
welp

### ISSUE THREAD

**Issue by krze** [brianmichel/Palmr#1]
I downloaded and installed xquartz and variant and started the step by step instructions. First issue I ran into when I tried `vagrant up` was it said I had no virtual environment, so I installed virtualbox like it asked me to.

Box went up. Proceeded through the rest of the instructions successfully, then on step 5 when I tried `vagrant -c ssh pose` I get this:

```
iKrebs-iMac:Palmr krebintosh$ vagrant ssh -c pose
Can't open display:
Connection to 127.0.0.1 closed.
iKrebs-iMac:Palmr krebintosh$ vagrant ssh -c pose
Can't open display:
Connection to 127.0.0.1 closed.
iKrebs-iMac:Palmr krebintosh$ vagrant ssh -c pose
Can't open display:
Connection to 127.0.0.1 closed.
iKrebs-iMac:Palmr krebintosh$
```

**Comment by krze** [comment]
Also what's the debian-etch login
<img width="804" alt="screen shot 2016-08-13 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/10662717/17644436/ab195796-6154-11e6-8ed6-f8369c585aa9.png">

**Comment by brianmichel** [comment]
Looks like I missed the "log back into your account after installing XQuartz".

After this has been completed @krze has been able to show the emulator.
